#!/usr/bin/ruby

require_relative 'func/fib'

#=====================================================================
# ** Problem 2
#---------------------------------------------------------------------
#  * Each new term in the Fibonacci sequence is generated by adding
#    the previous two terms. By starting with 1 and 2, the first 10
#    terms will be:
#
#      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#  * By considering the terms in the Fibonacci sequence whose values
#    do not exceed four million, find the sum of the even-valued
#    terms.
#=====================================================================
def main
  answer = 0
  fib_n = 0
  while true
    fib_r = fib fib_n
    fib_n += 1
    if fib_r <= 4000000
      if fib_r % 2 == 0
        answer += fib_r
      end
    else
      break
    end
  end
  
  puts "2\t: #{answer}"
end

main

