#!/usr/bin/python2
"""
Even Fibonacci numbers
======================
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

from __future__ import print_function
from shared import fibonacci


def run():
    value = 0
    fibonacci_counter = 0
    while True:
        fibonacci_value = fibonacci(fibonacci_counter)
        fibonacci_counter += 1
        if fibonacci_value < 4000000:
            value += fibonacci_value if fibonacci_value % 2 is 0 else 0
        else:
            break
    return 2, value

if __name__ == '__main__':
    from timeit import timeit
    timeit(run)
